name: Ping Render App Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:        # Optional manual trigger

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up Render app
        run: |
          echo "Pinging $RENDER_URL to prevent sleep..."
          curl -s -o /dev/null -w "HTTP status: %{http_code}\n" --max-time 10 "$RENDER_URL"
        env:
          RENDER_URL: ${{ secrets.RENDER_URL }}
