name: Hourly Trigger Anycross

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:         # Optional: allows manual trigger via GitHub UI

jobs:
  trigger-anycross:
    runs-on: ubuntu-latest

    steps:
      - name: Call Anycross webhook
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          PAYLOAD=$(jq -n --arg src "github-action" --arg time "$TIMESTAMP" '{source: $src, time: $time}')
          echo "Sending payload: $PAYLOAD"
          curl -X POST "$RENDER_URL" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
        env:
          ANYCROSS_URL: ${{ secrets.RENDER_URL }}

